version: '2.1'

services:
  app:
    build:
      context: .
    working_dir: "/app"
    volumes:
      - "./:/app/"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8081:8081/udp"
      - "6060:6060"

  srt:
    build:
      context: .
      dockerfile: Dockerfile-srt-live
    entrypoint: sh
    command: "./srt.sh"
    working_dir: "/scripts"
    volumes:
      - "./scripts:/scripts"
    environment:
      - SRT_LISTENING_PORT=40052
      - SRT_UDP_TS_INPUT_HOST=0.0.0.0
      - SRT_UDP_TS_INPUT_PORT=1234
    ports:
      - "40052:40052/udp"
    depends_on:
      - app
    links:
      - app

  origin: # simulating an mpeg-ts upd origin live transmission
    image: jrottenberg/ffmpeg:4.4-alpine
    entrypoint: sh
    command: "/scripts/ffmpeg_mpegts_udp.sh"
    volumes:
      - "./scripts:/scripts"
    environment:
      - SRT_INPUT_HOST=srt
      - SRT_INPUT_PORT=1234
      - PKT_SIZE=1316
    depends_on:
      - srt
    links:
      - srt

